version: "3.8"
services:
  db:
    image: mysql  #7.27-8.0.21
    container_name: amberdata_mysql
    privileged: true
    restart: always
    volumes:
      - ./../mysql:/var/lib/mysql
      - ./../conf:/etc/mysql/conf.d
      - ./../logs:/logs
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=AmberTest
      - TZ=Asia/Shanghai
    networks:
      - ambernet

  django_redis:
    image: redis
    container_name: amberdata_redis
    privileged: true
    restart: always
    ports:
      - "6379:6379"
#    volumes:
#      - /amberdata/redis/data:/data
#    command: ["redis-server", "--appendonly", "yes", "--requirepass", "Dctm@1234"]
    environment:
      - TZ=Asia/Shanghai
    networks:
      - ambernet

  web:
    build: .
    container_name: amberdata_zhuzh
    privileged: true
    command: bash start.sh
    restart: always
    volumes:
      - ./:/docker_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - ambernet


networks:
  ambernet:
    driver: bridge