#!/bin/bash
#注意：首次登入阿里云镜像仓库成功后会有一个警告，意思你的密码以明文格式记录在/root/.docker/config.json，
# 之生登录不需要密码了，如查要删了自己去找那个json文件就行
Username="zhuzhanhao"
Registry_Domain="registry.cn-hangzhou.aliyuncs.com"
Registry_Addr="${Registry_Domain}/zhuzhanhao/zhuzh"
#Password="XXXXX"

#登录阿里云镜像库，这里已经登录过阿里云镜像库了，则不加密码了
docker login --username=${Username} ${Registry_Domain} # -p${Password}
#停止容器并删除容器
docker stop amberdata_zhuzh && docker rm amberdata_zhuzh
#删除之前的镜像
docker rmi ${Registry_Domain}/:1.0
#拉取镜像并实例化容器运行
docker run -d -p 8000:8000 \
      --name amberdata_zhuzh \
      --restart=always \
      -v /amberdata/Easytest:/usr/src/app \
      ${Registry_Addr}/1.0



