# Generated by Django 3.0.5 on 2020-07-12 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50, verbose_name='计划名称')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='计划描述')),
                ('ploy', models.CharField(max_length=50, verbose_name='策略')),
                ('notification', models.BooleanField(verbose_name='消息通知')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
            ],
            options={
                'verbose_name_plural': '执行计划',
            },
        ),
        migrations.CreateModel(
            name='InterFaceCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_case_name', models.CharField(max_length=50, verbose_name='接口用例名称')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('pass_rate', models.CharField(blank=True, default='100', max_length=8, null=True, verbose_name='通过率')),
                ('create_data', models.DateField(auto_now=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '接口用例表',
                'verbose_name_plural': '接口用例表',
            },
        ),
        migrations.CreateModel(
            name='InterfaceCaseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_case_set_name', models.CharField(max_length=50, verbose_name='接口用例集名称')),
            ],
            options={
                'verbose_name_plural': '接口用例集',
            },
        ),
        migrations.CreateModel(
            name='InterFaceManageClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=50, verbose_name='系统分类标题')),
            ],
            options={
                'verbose_name': '接口管理-接入系统',
                'verbose_name_plural': '接口管理-接入系统',
            },
        ),
        migrations.CreateModel(
            name='InterFaceManageModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puisne_module', models.CharField(max_length=50, verbose_name='下属模块标题')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('create_data', models.DateField(auto_now=True, null=True, verbose_name='创建时间')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.InterFaceManageClassification', verbose_name='下属模块')),
            ],
            options={
                'verbose_name': '接口管理-下属模块',
                'verbose_name_plural': '接口管理-下属模块',
            },
        ),
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('icon', models.CharField(max_length=50, verbose_name='图标')),
                ('href', models.CharField(max_length=100, verbose_name='链接')),
                ('spread', models.BooleanField(default=False, verbose_name='默认不展开')),
            ],
            options={
                'verbose_name': '主菜单',
                'verbose_name_plural': '主菜单管理',
            },
        ),
        migrations.CreateModel(
            name='RelevanceCaseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_case_name', models.CharField(max_length=50, verbose_name='关联用例名称')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='关联用例描述')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.InterfaceCaseSet', verbose_name='接口集用例id')),
                ('relevance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.InterFaceCase', verbose_name='关联用例id')),
            ],
            options={
                'verbose_name_plural': '关联用例名称',
            },
        ),
        migrations.CreateModel(
            name='InterFaceSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(max_length=100, verbose_name='接口名称')),
                ('tcp', models.CharField(default='http', max_length=20, verbose_name='传输协议')),
                ('ip', models.CharField(max_length=50, verbose_name='访问路径')),
                ('url', models.CharField(max_length=550, verbose_name='访问路径')),
                ('method', models.CharField(max_length=20, verbose_name='请求方式')),
                ('headers', models.CharField(blank=True, max_length=200, null=True, verbose_name='请求头')),
                ('params', models.TextField(blank=True, null=True, verbose_name='请求参数')),
                ('body', models.TextField(blank=True, null=True, verbose_name='请求体内容')),
                ('preprocessor', models.CharField(default=False, max_length=20, verbose_name='前置处理器')),
                ('depend_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='依赖的id')),
                ('depend_key', models.CharField(blank=True, max_length=500, null=True, verbose_name='依赖的key')),
                ('replace_key', models.CharField(blank=True, max_length=500, null=True, verbose_name='替换的key')),
                ('replace_position', models.CharField(blank=True, max_length=50, null=True, verbose_name='替换的内容区域')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='响应时长')),
                ('result', models.TextField(blank=True, null=True, verbose_name='执行结果')),
                ('belong_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.InterFaceManageModule', verbose_name='所属模块的id')),
            ],
            options={
                'verbose_name_plural': '接口集管理',
            },
        ),
        migrations.CreateModel(
            name='InterFaceCaseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(max_length=50, verbose_name='接口名称')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('head', models.CharField(blank=True, max_length=20, null=True, verbose_name='负责人')),
                ('tcp', models.CharField(default='http', max_length=20, verbose_name='传输协议')),
                ('ip', models.CharField(max_length=50, verbose_name='访问路径')),
                ('url', models.CharField(max_length=550, verbose_name='访问路径')),
                ('method', models.CharField(max_length=20, verbose_name='请求方式')),
                ('headers', models.CharField(blank=True, max_length=200, null=True, verbose_name='请求头')),
                ('params', models.TextField(blank=True, null=True, verbose_name='请求参数')),
                ('body', models.TextField(blank=True, null=True, verbose_name='请求体内容')),
                ('preprocessor', models.CharField(default=False, max_length=20, verbose_name='前置处理器')),
                ('depend_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='依赖的id')),
                ('depend_key', models.CharField(blank=True, max_length=500, null=True, verbose_name='依赖的key')),
                ('replace_key', models.CharField(blank=True, max_length=500, null=True, verbose_name='替换的key')),
                ('replace_position', models.CharField(blank=True, max_length=50, null=True, verbose_name='替换的内容区域')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='响应时长')),
                ('result', models.TextField(blank=True, null=True, verbose_name='执行结果')),
                ('interface_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.InterFaceSet', verbose_name='关联接口id')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.InterFaceCase', verbose_name='接口用例id')),
            ],
            options={
                'verbose_name': '接口用例数据',
                'verbose_name_plural': '接口用例数据',
            },
        ),
        migrations.CreateModel(
            name='ExecutePlanReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fail_case_count', models.IntegerField(blank=True, null=True, verbose_name='失败用例数')),
                ('all_case_count', models.IntegerField(verbose_name='所有用例数')),
                ('fail_interface_count', models.IntegerField(blank=True, null=True, verbose_name='失败接口数')),
                ('all_interface_count', models.IntegerField(blank=True, null=True, verbose_name='所有接口数')),
                ('status', models.BooleanField(verbose_name='报告状态')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.ExecutePlan', verbose_name='执行计划id')),
            ],
            options={
                'verbose_name_plural': '测试报告',
            },
        ),
        migrations.CreateModel(
            name='ExecutePlanCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_case_set_name', models.CharField(max_length=50, verbose_name='关联用例集名称')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='关联用例集描述')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.ExecutePlan', verbose_name='执行计划id')),
                ('relevance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.InterfaceCaseSet', verbose_name='关联用例集id')),
            ],
            options={
                'verbose_name_plural': '关联用例集名称',
            },
        ),
        migrations.CreateModel(
            name='ChildMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('icon', models.CharField(max_length=50, verbose_name='图标')),
                ('href', models.CharField(max_length=100, verbose_name='链接')),
                ('spread', models.BooleanField(default=False, verbose_name='默认不展开')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.MainMenu', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '二级菜单',
                'verbose_name_plural': '二级菜单管理',
            },
        ),
    ]
