# Generated by Django 3.0.5 on 2020-06-06 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=150, verbose_name='区域')),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('icon', models.CharField(max_length=150, verbose_name='图标')),
                ('href', models.CharField(max_length=150, verbose_name='链接')),
                ('spread', models.BooleanField(default=False, verbose_name='默认不展开')),
                ('children', models.TextField(default=[], verbose_name='子菜单')),
            ],
            options={
                'verbose_name': '主菜单',
                'verbose_name_plural': '主菜单管理',
            },
        ),
        migrations.CreateModel(
            name='ChildMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('icon', models.CharField(max_length=150, verbose_name='图标')),
                ('href', models.CharField(max_length=150, verbose_name='链接')),
                ('spread', models.BooleanField(default=False, verbose_name='默认不展开')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.MainMenu', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '二级菜单',
                'verbose_name_plural': '二级菜单管理',
            },
        ),
    ]
