# Generated by Django 3.0.5 on 2020-06-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainmenu',
            name='area',
        ),
    ]
