# Generated by Django 3.0.5 on 2020-07-14 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0002_remove_interfacecasedata_interface_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interfaceset',
            name='depend_id',
        ),
        migrations.RemoveField(
            model_name='interfaceset',
            name='depend_key',
        ),
        migrations.RemoveField(
            model_name='interfaceset',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='interfaceset',
            name='replace_key',
        ),
        migrations.RemoveField(
            model_name='interfaceset',
            name='replace_position',
        ),
        migrations.RemoveField(
            model_name='interfaceset',
            name='result',
        ),
    ]
