# Generated by Django 3.0.5 on 2020-06-07 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0002_remove_mainmenu_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterFaceManageClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Classification', models.CharField(max_length=50, verbose_name='系统分类标题')),
            ],
        ),
        migrations.AlterField(
            model_name='childmenu',
            name='href',
            field=models.CharField(max_length=100, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='childmenu',
            name='icon',
            field=models.CharField(max_length=50, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='childmenu',
            name='title',
            field=models.CharField(max_length=50, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='href',
            field=models.CharField(max_length=100, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='icon',
            field=models.CharField(max_length=50, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='title',
            field=models.CharField(max_length=50, verbose_name='标题'),
        ),
        migrations.CreateModel(
            name='InterFaceManageModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, verbose_name='链接')),
                ('puisne_module', models.CharField(max_length=50, verbose_name='下属模块标题')),
                ('puisne_key', models.CharField(max_length=50, verbose_name='下属模块的键')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.InterFaceManageClassification', verbose_name='下属模块')),
            ],
        ),
    ]
