# Generated by Django 3.0.5 on 2020-06-07 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0003_auto_20200607_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interfacemanageclassification',
            options={'verbose_name': '接口管理-接入系统', 'verbose_name_plural': '接口管理-接入系统'},
        ),
        migrations.AlterModelOptions(
            name='interfacemanagemodule',
            options={'verbose_name': '接口管理-下属模块', 'verbose_name_plural': '接口管理-下属模块'},
        ),
        migrations.RenameField(
            model_name='interfacemanageclassification',
            old_name='Classification',
            new_name='classification',
        ),
    ]
