# Generated by Django 3.0.5 on 2020-06-11 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0005_interfaceset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interfaceset',
            options={'verbose_name_plural': '接口集管理'},
        ),
        migrations.RenameField(
            model_name='interfaceset',
            old_name='header',
            new_name='headers',
        ),
        migrations.RemoveField(
            model_name='interfaceset',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='interfaceset',
            name='exceptres',
        ),
        migrations.RemoveField(
            model_name='interfaceset',
            name='head',
        ),
        migrations.RemoveField(
            model_name='interfaceset',
            name='identity',
        ),
        migrations.RemoveField(
            model_name='interfaceset',
            name='result',
        ),
        migrations.RemoveField(
            model_name='interfaceset',
            name='sortid',
        ),
        migrations.AlterField(
            model_name='interfaceset',
            name='belong_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.InterFaceManageModule', verbose_name='所属模块的id'),
        ),
    ]
