# Generated by Django 3.0.3 on 2020-06-12 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0006_auto_20200611_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainmenu',
            name='children',
        ),
    ]
