# Generated by Django 3.0.5 on 2020-06-12 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0007_remove_mainmenu_children'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceCaseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_case_set_name', models.CharField(max_length=50, verbose_name='接口用例集名称')),
            ],
            options={
                'verbose_name_plural': '接口用例集',
            },
        ),
        migrations.AddField(
            model_name='interfaceset',
            name='duration',
            field=models.FloatField(blank=True, null=True, verbose_name='响应时长'),
        ),
        migrations.AddField(
            model_name='interfaceset',
            name='head',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='interfaceset',
            name='result',
            field=models.TextField(blank=True, null=True, verbose_name='执行结果'),
        ),
        migrations.CreateModel(
            name='InterFaceCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_case_name', models.CharField(max_length=50, verbose_name='接口用例名称')),
                ('interface_id', models.IntegerField(max_length=20, verbose_name='接口id')),
                ('interface_name', models.CharField(max_length=50, verbose_name='接口名称')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.InterfaceCaseSet', verbose_name='接口用例集id')),
            ],
            options={
                'verbose_name': '接口用例名称',
                'verbose_name_plural': '接口用例名称',
            },
        ),
    ]
