# Generated by Django 3.0.5 on 2020-06-13 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0008_auto_20200612_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interfacecase',
            options={'verbose_name': '接口用例表', 'verbose_name_plural': '接口用例表'},
        ),
        migrations.RemoveField(
            model_name='interfacecase',
            name='interface_id',
        ),
        migrations.RemoveField(
            model_name='interfacecase',
            name='interface_name',
        ),
        migrations.AddField(
            model_name='interfacecaseset',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='描述'),
        ),
        migrations.CreateModel(
            name='InterFaceCaseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_id', models.IntegerField(max_length=20, verbose_name='关联接口id')),
                ('interface_name', models.CharField(max_length=50, verbose_name='接口名称')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.InterFaceCase', verbose_name='接口用例id')),
            ],
            options={
                'verbose_name': '接口用例数据',
                'verbose_name_plural': '接口用例数据',
            },
        ),
    ]
