# Generated by Django 3.0.5 on 2020-06-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0010_auto_20200613_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacecase',
            name='create_data',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='interfacecaseset',
            name='create_data',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间'),
        ),
    ]
