# Generated by Django 3.0.5 on 2020-06-14 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0013_auto_20200613_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacecasedata',
            name='interface_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.InterFaceSet', verbose_name='关联接口id'),
        ),
    ]
