# Generated by Django 3.0.5 on 2020-06-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0014_auto_20200614_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfaceset',
            name='ip',
            field=models.CharField(default='', max_length=50, verbose_name='访问路径'),
            preserve_default=False,
        ),
    ]
