# Generated by Django 3.0.5 on 2020-06-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0015_interfaceset_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfaceset',
            name='tcp',
            field=models.CharField(default='http', max_length=20, verbose_name='传输协议'),
        ),
    ]
