# Generated by Django 3.0.5 on 2020-06-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0016_interfaceset_tcp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interfaceset',
            name='head',
        ),
        migrations.AddField(
            model_name='interfacecasedata',
            name='head',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='负责人'),
        ),
    ]
