# Generated by Django 3.0.5 on 2020-06-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0017_auto_20200614_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaceset',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='响应时长'),
        ),
    ]
