# Generated by Django 3.0.3 on 2020-06-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0017_auto_20200614_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacecase',
            name='pass_rate',
            field=models.CharField(blank=True, default='100', max_length=8, null=True, verbose_name='通过率'),
        ),
    ]
