# Generated by Django 3.0.5 on 2020-06-17 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0018_auto_20200617_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interfacecaseset',
            name='create_data',
        ),
        migrations.RemoveField(
            model_name='interfacecaseset',
            name='description',
        ),
        migrations.RemoveField(
            model_name='interfacecaseset',
            name='relevance_ids',
        ),
        migrations.CreateModel(
            name='RelevanceCaseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_case_name', models.CharField(max_length=50, verbose_name='关联用例名称')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='关联用例描述')),
                ('relevance_id', models.CharField(max_length=255, verbose_name='关联用例id')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.InterfaceCaseSet', verbose_name='接口集用例id')),
            ],
            options={
                'verbose_name_plural': '关联用例名称',
            },
        ),
    ]
