# Generated by Django 3.0.5 on 2020-06-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0019_auto_20200617_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interfacemanagemodule',
            name='puisne_key',
        ),
        migrations.RemoveField(
            model_name='interfacemanagemodule',
            name='url',
        ),
        migrations.AddField(
            model_name='interfacemanagemodule',
            name='create_data',
            field=models.DateField(auto_now=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='interfacemanagemodule',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='描述'),
        ),
    ]
