# Generated by Django 3.0.5 on 2020-06-22 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0018_interfacecase_pass_rate'),
        ('easy', '0020_auto_20200619_2130'),
    ]

    operations = [
    ]
