# Generated by Django 3.0.5 on 2020-06-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0021_merge_20200622_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50, verbose_name='计划名称')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='计划描述')),
                ('ploy', models.CharField(max_length=50, verbose_name='策略')),
                ('notification', models.BooleanField(verbose_name='消息通知')),
                ('status', models.BooleanField(verbose_name='计划状态')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
            ],
            options={
                'verbose_name_plural': '执行计划',
            },
        ),
    ]
