# Generated by Django 3.0.5 on 2020-06-23 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0022_executeplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutePlanCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_case_set_name', models.CharField(max_length=50, verbose_name='关联用例集名称')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='关联用例集描述')),
                ('relevance_id', models.CharField(max_length=255, verbose_name='关联用例集id')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.InterfaceCaseSet', verbose_name='执行计划id')),
            ],
        ),
    ]
