# Generated by Django 3.0.5 on 2020-06-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0023_executeplancases'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executeplancases',
            options={'verbose_name_plural': '关联用例集名称'},
        ),
        migrations.AlterField(
            model_name='executeplancases',
            name='relevance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.InterFaceCase', verbose_name='关联用例集id'),
        ),
        migrations.AlterField(
            model_name='relevancecaseset',
            name='relevance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.InterFaceCase', verbose_name='关联用例id'),
        ),
    ]
