# Generated by Django 3.0.5 on 2020-06-27 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0024_auto_20200624_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executeplancases',
            name='relevance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.RelevanceCaseSet', verbose_name='关联用例集id'),
        ),
    ]
