# Generated by Django 3.0.5 on 2020-07-05 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0028_auto_20200701_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutePlanReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_rate', models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='通过率')),
                ('status', models.BooleanField(verbose_name='报告状态')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.ExecutePlan', verbose_name='执行计划id')),
            ],
            options={
                'verbose_name_plural': '测试报告',
            },
        ),
        migrations.DeleteModel(
            name='ExecutePlanExport',
        ),
    ]
